### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by DevMukhtarr** [DevMukhtarr/notify#2]
I am getting [A token is required for authentication] while trying to access the alerts page, I tested it using postman and it's working fine but i can't figure out the issue from the frontend @Taiwrash

**Comment by Taiwrash** [comment]
oh, The token saved in browser. have you confirmed whether it has expired or not?

**Comment by DevMukhtarr** [comment]
Yeah i checked it is still valid, works well with postman looks like it's an issue with sending from frontend

**Comment by Taiwrash** [comment]
Let's log token before fetching and see.


```js
const jwtToken = localStorage.getItem('x-access-token');

console.log('Token:', jwtToken);

fetch('/alerts', {
  method: 'GET',
  headers: {
      'Content-Type': 'application/json',
      'x-access-token': `${jwtToken}`,
  },
})
  .then(response => response.json())
  .then(data => {
    // Process the response data as needed
    console.log(data);
  })
  .catch(error => {
    console.error('Request failed:', error);
  });
```

**Comment by DevMukhtarr** [comment]
I added it, not logging anything to console
<img width="291" alt="Screenshot 2023-12-08 191001" src="https://github.com/DevMukhtarr/notify/assets/50122611/06bfe459-82aa-4efa-967b-e00078b6f0c8">

**Comment by Taiwrash** [comment]
that means there is issues saving it in the localstorage

=== can you check the storage manually if there is anything in it after login?

**Comment by Taiwrash** [comment]
log out and re-login

**Comment by DevMukhtarr** [comment]
yeah i did that, the token is showing in localstorage
<img width="321" alt="Screenshot 2023-12-08 192358" src="https://github.com/DevMukhtarr/notify/assets/50122611/e59d7c78-fca9-437c-9b0e-99c9ba0073f1">

**Comment by Taiwrash** [comment]
Try and clear it manually and login again. 

Let's find why it is not logging before fetching in alerts

**Comment by DevMukhtarr** [comment]
Alright let me do that right away

**Comment by DevMukhtarr** [comment]
I just did that, still not logging

**Comment by Taiwrash** [comment]
<img width="1440" alt="Screenshot 2023-12-08 at 20 44 11" src="https://github.com/DevMukhtarr/notify/assets/49725691/864560e8-65bb-4ea1-a5bd-c34927bb7117">

**Comment by Taiwrash** [comment]
@DevMukhtarr I was able to login

**Comment by DevMukhtarr** [comment]
nice, there's something i noticed

**Comment by Taiwrash** [comment]
okay
<img width="1440" alt="Screenshot 2023-12-08 at 20 47 47" src="https://github.com/DevMukhtarr/notify/assets/49725691/6e935ffb-fa57-4dfc-8f9b-c4548a4f54ee">

**Comment by DevMukhtarr** [comment]
when i logged this to console
`console.log('Token:', localStorage.getItem('x-access-token'))`
the jwt showed, it then it went to the alert page and showed that same error

**Comment by DevMukhtarr** [comment]
Alert is not showing in yours, looks like it hasn't been pushed

**Comment by DevMukhtarr** [comment]
I have added it

**Comment by Taiwrash** [comment]
> okay <img alt="Screenshot 2023-12-08 at 20 47 47" width="1440" src="https://private-user-images.githubusercontent.com/49725691/289174951-6e935ffb-fa57-4dfc-8f9b-c4548a4f54ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjUxOTUsIm5iZiI6MTcwMjA2NDg5NSwicGF0aCI6Ii80OTcyNTY5MS8yODkxNzQ5NTEtNmU5MzVmZmItZmE1Ny00ZGZjLThmOWItYzQ1NDhhNGY1NGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE5NDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZjNkOWVlNzIxZWNmODYzNGQ2NjMwZTE4ZDJiNGIzNWIzNTUzYjM1YWY3OGRiNTFmNzNkMjZlYTg4MjQ2MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ITMSsTs5Ubv1IiWuPePkxVmqnmEm6INbIcsvtvqNIt0">

Here is the error.... Nothing is saved in the localstorage

**Comment by DevMukhtarr** [comment]
Ooh i thought this was supposed to handle it in both register and login page 
`localStorage.setItem('x-access-token', jwtToken);`
